Repository LikeMindsCommunity/likeminds-feed-reactnative, pull requests merged in 2024-11, with the labels that each got.

#99 [LM-13040] Video Compression and Crashes
  likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostAttachmentSelection.tsx
  likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostMedia.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCreatePostCarousel/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCreatePostVideo/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/index.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPost/index.tsx
  likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
  likeminds-feed-reactnative-integration/context/createPostContext.tsx
  likeminds-feed-reactnative-integration/context/postItemContext.tsx
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/createPost/styles.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/setup.ts
  qna-feed/package.json
  social-feed/package.json
  social-feed/react-native.config.js
Labels: bug, enhancement

#100 [WIP][LM-13017] User Onboarding
  likeminds-feed-reactnative-integration/assets/images/camera_3x.png
  likeminds-feed-reactnative-integration/assets/images/edit_profile3x.png
  likeminds-feed-reactnative-integration/assets/images/oval_3x.png
  likeminds-feed-reactnative-integration/assets/images/user_3x.png
  likeminds-feed-reactnative-integration/components/LMLoader/index.tsx
  likeminds-feed-reactnative-integration/components/LMLoader/types.ts
  likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
  likeminds-feed-reactnative-integration/constants/Styles.ts
  likeminds-feed-reactnative-integration/constants/screenNames.ts
  likeminds-feed-reactnative-integration/context/index.ts
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/context/userOnboardingCallbacksContext.tsx
  likeminds-feed-reactnative-integration/context/userOnboardingContext.tsx
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
  likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
  likeminds-feed-reactnative-integration/models/RootStackParamsList.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/index.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
  likeminds-feed-reactnative-integration/store/types/types.ts
  likeminds-feed-reactnative-integration/utils/mediaSelection.ts
  likeminds-feed-reactnative-integration/utils/uploadFilesToAWS.ts
  likeminds-feed-reactnative-integration/wrappers/index.ts
  likeminds-feed-reactnative-integration/wrappers/userOnboardingScreenWrapper.tsx
  qna-feed/package.json
  social-feed/App.tsx
  social-feed/login/index.tsx
  social-feed/package.json
Labels: enhancement

#101 Release/v1.11.0
  likeminds-feed-reactnative-integration/assets/images/camera_3x.png
  likeminds-feed-reactnative-integration/assets/images/edit_profile3x.png
  likeminds-feed-reactnative-integration/assets/images/oval_3x.png
  likeminds-feed-reactnative-integration/assets/images/user_3x.png
  likeminds-feed-reactnative-integration/components/LMCreatePost/LMCreatePostUserTagging.tsx
  likeminds-feed-reactnative-integration/components/LMLoader/index.tsx
  likeminds-feed-reactnative-integration/components/LMLoader/types.ts
  likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
  likeminds-feed-reactnative-integration/constants/Styles.ts
  likeminds-feed-reactnative-integration/constants/screenNames.ts
  likeminds-feed-reactnative-integration/context/index.ts
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/context/userOnboardingCallbacksContext.tsx
  likeminds-feed-reactnative-integration/context/userOnboardingContext.tsx
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
  likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
  likeminds-feed-reactnative-integration/models/RootStackParamsList.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/index.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
  likeminds-feed-reactnative-integration/store/types/types.ts
  likeminds-feed-reactnative-integration/utils/mediaSelection.ts
  likeminds-feed-reactnative-integration/utils/uploadFilesToAWS.ts
  likeminds-feed-reactnative-integration/wrappers/index.ts
  likeminds-feed-reactnative-integration/wrappers/userOnboardingScreenWrapper.tsx
  qna-feed/package.json
  social-feed/App.tsx
  social-feed/login/index.tsx
  social-feed/package.json
Labels: release

#102 [LM-13119] Feed Bugs
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/styles.ts
  likeminds-feed-reactnative-integration/context/userOnboardingContext.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
  likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/topicFeed/index.tsx
  likeminds-feed-reactnative-integration/screens/topicFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
  likeminds-feed-reactnative-integration/uiComponents/LMInputText/utils.ts
  qna-feed/package.json
  social-feed/package.json
Labels: bug, enhancement

#103 Release/v1.11.1
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/styles.ts
  likeminds-feed-reactnative-integration/context/userOnboardingContext.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
  likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/topicFeed/index.tsx
  likeminds-feed-reactnative-integration/screens/topicFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/userOnboardingScreen/index.tsx
  likeminds-feed-reactnative-integration/uiComponents/LMInputText/utils.ts
  qna-feed/package.json
  social-feed/package.json
Labels: release

#104 [HOTFIX] TS Version
  likeminds-feed-reactnative-integration/package.json
Labels: hotfix
