Repository LikeMindsCommunity/likeminds-feed-reactnative, pull requests merged in 2024-08, with the labels that each got.

#67 [LM-12591] Font type support, UI Enhancements
  likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMCommentItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMFilterTopics/index.tsx
  likeminds-feed-reactnative-integration/components/LMHeader/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMDocument/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMImage/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMLinkPreview/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/styles.ts
  likeminds-feed-reactnative-integration/components/LMMemberListItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPoll/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPost/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostContent/styles.ts
  likeminds-feed-reactnative-integration/components/LMToast/styles.ts
  likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
  likeminds-feed-reactnative-integration/constants/Styles.ts
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/screens/LMFeedCreatePollScreen/index.tsx
  likeminds-feed-reactnative-integration/screens/LMPollResult/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/styles.ts
  likeminds-feed-reactnative-integration/screens/notificationFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/notificationsList/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/styles.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/uiComponents/LMText/styles.ts
  likeminds-feed-reactnative-integration/utils/decodeMentions.tsx
  likeminds-feed-reactnative-integration/utils/pushNotifications.ts
  likeminds-feed-reactnative-integration/wrappers/createPollScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/createScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/detailScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/index.ts
  likeminds-feed-reactnative-integration/wrappers/likesWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/notificationWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/topicFeedScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/universalFeedScreenWrapper.tsx
Labels: enhancement

#68 [v1.7.0] Version Upgrade
  example/package.json
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
Labels: enhancement

#69 Release/v1.7.0
  example/package.json
  likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMCommentItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMFilterTopics/index.tsx
  likeminds-feed-reactnative-integration/components/LMHeader/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMDocument/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMImage/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMLinkPreview/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/styles.ts
  likeminds-feed-reactnative-integration/components/LMMemberListItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPoll/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPost/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostContent/styles.ts
  likeminds-feed-reactnative-integration/components/LMToast/styles.ts
  likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
  likeminds-feed-reactnative-integration/constants/Styles.ts
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/LMFeedCreatePollScreen/index.tsx
  likeminds-feed-reactnative-integration/screens/LMPollResult/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/styles.ts
  likeminds-feed-reactnative-integration/screens/notificationFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/notificationsList/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/styles.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/uiComponents/LMText/styles.ts
  likeminds-feed-reactnative-integration/utils/decodeMentions.tsx
  likeminds-feed-reactnative-integration/utils/pushNotifications.ts
  likeminds-feed-reactnative-integration/wrappers/createPollScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/createScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/detailScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/index.ts
  likeminds-feed-reactnative-integration/wrappers/likesWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/notificationWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/topicFeedScreenWrapper.tsx
  likeminds-feed-reactnative-integration/wrappers/universalFeedScreenWrapper.tsx
Labels: release

#70 [LM-12608] Replies Overflow Menu
  example/App.tsx
  likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
  likeminds-feed-reactnative-integration/customModals/LMPostMenu/index.tsx
  likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
  likeminds-feed-reactnative-integration/models/LMCommentUI.ts
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/store/reducers/postDetailReducer.ts
  likeminds-feed-reactnative-integration/utils/commentResponseModelConvertor.ts
  likeminds-feed-reactnative-integration/viewDataModels/index.ts
Labels: bug

#71 [LM-12226] Migration: Target SDK 34
  example/App.tsx
  example/android/build.gradle
  example/package.json
  likeminds-feed-reactnative-integration/context/createPostContext.tsx
  likeminds-feed-reactnative-integration/package.json
Labels: enhancement

#72 [v.1.8.0] Version Upgrade
  example/package.json
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
Labels: enhancement

#73 Release/v1.8.0
  example/App.tsx
  example/android/build.gradle
  example/package.json
  likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
  likeminds-feed-reactnative-integration/context/createPostContext.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
  likeminds-feed-reactnative-integration/customModals/LMPostMenu/index.tsx
  likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
  likeminds-feed-reactnative-integration/models/LMCommentUI.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/store/reducers/postDetailReducer.ts
  likeminds-feed-reactnative-integration/utils/commentResponseModelConvertor.ts
  likeminds-feed-reactnative-integration/viewDataModels/index.ts
Labels: release

#74 [LM-12659] Peer Testing Bugs
  example/App.tsx
  example/components/FilterTopics/index.tsx
  likeminds-feed-reactnative-integration/components/LMCommentItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMFilterTopics/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/styles.ts
  likeminds-feed-reactnative-integration/components/LMPoll/CreatePollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPoll/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPost/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostHeader/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPostMedia/index.tsx
  likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
  likeminds-feed-reactnative-integration/constants/Styles.ts
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
  likeminds-feed-reactnative-integration/customModals/ReportModal/styles.ts
  likeminds-feed-reactnative-integration/screens/LMPollResult/index.tsx
  likeminds-feed-reactnative-integration/screens/carouselScreen/index.tsx
  likeminds-feed-reactnative-integration/screens/carouselScreen/styles.ts
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/styles.ts
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/styles.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/topicFeed/index.tsx
  likeminds-feed-reactnative-integration/screens/topicFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/uiComponents/LMProfilePicture/styles.ts
Labels: bug

#75 [v.1.8.1] Version Upgrade
  example/package.json
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
Labels: enhancement

#76 Release/v1.8.1
  example/App.tsx
  example/components/FilterTopics/index.tsx
  example/package.json
  likeminds-feed-reactnative-integration/components/LMCommentItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMFilterTopics/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/styles.ts
  likeminds-feed-reactnative-integration/components/LMPoll/CreatePollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPoll/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPost/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostHeader/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPostMedia/index.tsx
  likeminds-feed-reactnative-integration/components/LMUniversalFeedHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMVideoPlayer/index.tsx
  likeminds-feed-reactnative-integration/constants/Styles.ts
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/customModals/ReportModal/index.tsx
  likeminds-feed-reactnative-integration/customModals/ReportModal/styles.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/LMPollResult/index.tsx
  likeminds-feed-reactnative-integration/screens/carouselScreen/index.tsx
  likeminds-feed-reactnative-integration/screens/carouselScreen/styles.ts
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/styles.ts
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/styles.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/topicFeed/index.tsx
  likeminds-feed-reactnative-integration/screens/topicFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/universalFeed/styles.ts
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/uiComponents/LMProfilePicture/styles.ts
Labels: release
