Repository LikeMindsCommunity/likeminds-feed-reactnative, pull requests merged in 2024-04, with the labels that each got.

#23 [LM-10433] Added Notification
  example/SampleApp/sampleApp/.gitignore
  example/SampleApp/sampleApp/App.tsx
  example/SampleApp/sampleApp/feedScreen/feed.tsx
  example/SampleApp/sampleApp/feedScreen/notificationScreen.tsx
  example/SampleApp/sampleApp/feedScreen/notificationWrapper.tsx
  example/SampleApp/sampleApp/index.js
  example/SampleApp/sampleApp/ios/sampleApp.xcodeproj/project.pbxproj
  example/SampleApp/sampleApp/ios/sampleApp/AppDelegate.mm
  example/SampleApp/sampleApp/ios/sampleApp/sampleApp.entitlements
  example/SampleApp/sampleApp/package.json
  example/SampleApp/sampleApp/pushNotification.ts
  example/SampleApp/sampleApp/registerDeviceApi.ts
  likeminds-feed-reactnative-integration/assets/images/no_notification.png
  likeminds-feed-reactnative-integration/assets/images/notification_bell.png
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/types.ts
  likeminds-feed-reactnative-integration/constants/Strings.ts
  likeminds-feed-reactnative-integration/constants/screenNames.ts
  likeminds-feed-reactnative-integration/context/index.ts
  likeminds-feed-reactnative-integration/context/notificationFeedCallbacksContext.tsx
  likeminds-feed-reactnative-integration/context/notificationFeedContext.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedCallbacksContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/lmOverlayProvider/index.tsx
  likeminds-feed-reactnative-integration/lmOverlayProvider/types.ts
  likeminds-feed-reactnative-integration/models/LMActivityEntityUI.ts
  likeminds-feed-reactnative-integration/models/RootStackParamsList.ts
  likeminds-feed-reactnative-integration/notification/index.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/index.ts
  likeminds-feed-reactnative-integration/screens/notificationFeed/index.tsx
  likeminds-feed-reactnative-integration/screens/notificationFeed/styles.ts
  likeminds-feed-reactnative-integration/screens/notificationsList/index.tsx
  likeminds-feed-reactnative-integration/screens/notificationsList/styles.ts
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
  likeminds-feed-reactnative-integration/store/actions/notification.ts
  likeminds-feed-reactnative-integration/store/apiMiddleware.ts
  likeminds-feed-reactnative-integration/store/contextStore.tsx
  likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
  likeminds-feed-reactnative-integration/store/reducers/notificationReducer.ts
  likeminds-feed-reactnative-integration/store/store.ts
  likeminds-feed-reactnative-integration/store/types/types.ts
  likeminds-feed-reactnative-integration/tsconfig.json
  likeminds-feed-reactnative-integration/viewDataModels/index.ts
Labels: enhancement

#24 [LM-10435] Added share post
  example/SampleApp/sampleApp/App.tsx
  example/SampleApp/sampleApp/feedScreen/feed.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/index.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedCallbacksContext.tsx
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
Labels: enhancement

#25 [LM-10996] Video auto play/pause functionality
  example/SampleApp/sampleApp/feedScreen/feed.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/types.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPostMedia/index.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/context/postListContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
Labels: enhancement

#28 [LM -11099] Resolved peer testing bugs
  likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMCommentItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMMedia/LMCarousel/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/index.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMVideo/types.ts
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPostHeader/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostMedia/index.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/context/postListContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedCallbacksContext.tsx
  likeminds-feed-reactnative-integration/customModals/DeleteModal/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/universalFeed/index.tsx
  likeminds-feed-reactnative-integration/uiComponents/LMText/index.tsx
Labels: enhancement

#29 [LM-11116] Peer Testing R2
  likeminds-feed-reactnative-integration/components/LMMedia/LMScrollDocument/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/notificationsList/index.tsx
Labels: bug

#30 [LM-11099] resolved peer testing R2 bugs
  example/App.tsx
  example/android/app/src/main/AndroidManifest.xml
  example/feedScreen/detailScreen.tsx
  likeminds-feed-reactnative-integration/components/LMMedia/LMScrollDocument/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMNotificationFeedItem/styles.ts
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostFooter/styles.ts
  likeminds-feed-reactnative-integration/context/notificationFeedContext.tsx
  likeminds-feed-reactnative-integration/context/postDetailCallbacksContext.tsx
  likeminds-feed-reactnative-integration/context/postDetailContext.tsx
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/screens/createPost/index.tsx
  likeminds-feed-reactnative-integration/screens/notificationFeed/index.tsx
  likeminds-feed-reactnative-integration/screens/notificationsList/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/uiComponents/LMButton/index.tsx
Labels: bug

#31 [v1.0.0] - Version Upgrade
  example/package.json
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
Labels: enhancement

#32 Git Tag and Release Pipeline
  .github/workflows/create-tag-and-release.yml
Labels: enhancement

#35 [LM-11119] Resolved release v1 blockers
  likeminds-feed-reactnative-integration/components/LMCommentItem/index.tsx
  likeminds-feed-reactnative-integration/components/LMCommentItem/types.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/types.ts
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
Labels: bug

#37 [LM-11126] API Key Switcher
  example/App.tsx
  example/index.js
  example/login/credentials.ts
  example/login/index.tsx
  example/login/loginSchemaRO.ts
  example/package.json
Labels: enhancement

#38 [v1.0.1] Version Upgrade
  example/package.json
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
Labels: enhancement

#39 Release v1.0.1
  example/App.tsx
  example/index.js
  example/login/credentials.ts
  example/login/index.tsx
  example/login/loginSchemaRO.ts
  example/package.json
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
Labels: release
