Repository LikeMindsCommunity/likeminds-feed-reactnative, pull requests merged in 2025-01, with the labels that each got.

#109 [Hotfix] Gradle Build Issue
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
  qna-feed/package.json
  social-feed/package.json
Labels: hotfix

#110 [LM-11934] Personalised Feed
  likeminds-feed-reactnative-integration/components/LMPost/LMPostTopResponse/index.tsx
  likeminds-feed-reactnative-integration/context/postListContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/context/userOnboardingCallbacksContext.tsx
  likeminds-feed-reactnative-integration/enums/FeedType.ts
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/models/LMPostViewData.ts
  likeminds-feed-reactnative-integration/models/LMTopicViewData.ts
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/store/actions/feed.ts
  likeminds-feed-reactnative-integration/store/actions/postDetail.ts
  likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
  likeminds-feed-reactnative-integration/store/types/types.ts
  likeminds-feed-reactnative-integration/utils/debounce.ts
  likeminds-feed-reactnative-integration/viewDataModels/index.ts
  qna-feed/App.tsx
  social-feed/App.tsx
Labels: enhancement

#112 v1.12.0 PSO Bugs
  likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/models/LMWidgetData.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/styles.ts
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/store/apiMiddleware.ts
  likeminds-feed-reactnative-integration/viewDataModels/index.ts
  qna-feed/package.json
  social-feed/package.json
Labels: enhancement

#113 Release/v1.12.0
  likeminds-feed-reactnative-integration/components/LMPoll/LMPostPollUI/index.tsx
  likeminds-feed-reactnative-integration/components/LMPost/LMPostTopResponse/index.tsx
  likeminds-feed-reactnative-integration/context/postListContext.tsx
  likeminds-feed-reactnative-integration/context/universalFeedContext.tsx
  likeminds-feed-reactnative-integration/context/userOnboardingCallbacksContext.tsx
  likeminds-feed-reactnative-integration/enums/FeedType.ts
  likeminds-feed-reactnative-integration/index.ts
  likeminds-feed-reactnative-integration/lmFeedProvider/index.tsx
  likeminds-feed-reactnative-integration/models/LMPostViewData.ts
  likeminds-feed-reactnative-integration/models/LMTopicViewData.ts
  likeminds-feed-reactnative-integration/models/LMWidgetData.ts
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/screens/postDetail/index.tsx
  likeminds-feed-reactnative-integration/screens/postDetail/styles.ts
  likeminds-feed-reactnative-integration/screens/postsList/index.tsx
  likeminds-feed-reactnative-integration/setup.ts
  likeminds-feed-reactnative-integration/store/actions/feed.ts
  likeminds-feed-reactnative-integration/store/actions/postDetail.ts
  likeminds-feed-reactnative-integration/store/apiMiddleware.ts
  likeminds-feed-reactnative-integration/store/reducers/feedReducer.ts
  likeminds-feed-reactnative-integration/store/types/types.ts
  likeminds-feed-reactnative-integration/utils/debounce.ts
  likeminds-feed-reactnative-integration/viewDataModels/index.ts
  qna-feed/App.tsx
  qna-feed/package.json
  social-feed/App.tsx
  social-feed/package.json
Labels: release

#114 [LM-13428] Data Type issue
  likeminds-feed-reactnative-integration/package.json
  likeminds-feed-reactnative-integration/setup.ts
  qna-feed/package.json
  social-feed/package.json
Labels: hotfix
